#ifndef __CancerVCT_QSPParam__
#define __CancerVCT_QSPParam__

// Auto-generated by qsp_codegen.py from SBML — do not edit manually

#include "../ParamBase.h"

namespace CancerVCT{

class QSPParam : public ParamBase
{
public:
    QSPParam();
    ~QSPParam(){};
    double getVal(int n) const;
    void printParam(void) const;
private:
    std::vector<double> _param;
    void _readParameters(const std::string& filename);
    static const char* _xml_paths[];
};

}  // namespace CancerVCT
#endif
