#ifndef __CancerVCT_QSPParam__
#define __CancerVCT_QSPParam__

// Auto-generated by qsp_codegen.py from SBML — do not edit manually

#include "../../core/ParamBase.h"

namespace CancerVCT{

class QSPParam : public SP_QSP_IO::ParamBase
{
public:
    QSPParam();
    ~QSPParam(){};
    double getVal(int n) const;
    void printParam(void) const;
    bool readParamsFromXml(std::string inFileName) override {
        _readParameters(inFileName);
        return true;
    }
private:
    std::vector<double> _param;
    void _readParameters(const std::string& filename);
    static const char* _xml_paths[];
    void setupParam() override {}
    void processInternalParams() override {}
};

}  // namespace CancerVCT
#endif
