#include "gpu_param.h"
#include "flamegpu/flamegpu.h"
#include <iostream>

// Auto-generated by abm_param_codegen.py from param_all_test.xml — do not edit manually

namespace PDAC {

// XML path mappings - maps index to {XML_path, units, validation_type}
// validation_type: "pr" = positive real, "pos" = positive integer, "" = unconstrained
const char* _gpu_param_description[][3] = {
    // Float parameters
    {"Param.ABM.Environment.SecPerSlice", "seconds", "pos"},  // PARAM_SEC_PER_SLICE
    {"Param.ABM.Environment.recSiteFactor", "", "pos"},  // PARAM_REC_SITE_FACTOR
    {"Param.ABM.Environment.adhSiteDens", "", "pos"},  // PARAM_ADH_SITE_DENSITY
    {"Param.ABM.Pharmacokinetics.nivoDoseIntervalTime", "", "pr"},  // PARAM_NIVO_DOSE_INTERVAL_TIME
    {"Param.ABM.Pharmacokinetics.nivoDose", "", "pr"},  // PARAM_NIVO_DOSE
    {"Param.ABM.Pharmacokinetics.ipiDoseIntervalTime", "", "pr"},  // PARAM_IPI_DOSE_INTERVAL_TIME
    {"Param.ABM.Pharmacokinetics.ipiDose", "", "pr"},  // PARAM_IPI_DOSE
    {"Param.ABM.Pharmacokinetics.caboDoseIntervalTime", "", "pr"},  // PARAM_CABO_DOSE_INTERVAL_TIME
    {"Param.ABM.Pharmacokinetics.caboDose", "", "pr"},  // PARAM_CABO_DOSE
    {"Param.ABM.cell.PDL1_th", "", "pr"},  // PARAM_PDL1_TH
    {"Param.ABM.cell.IFNg_PDL1_half", "", "pr"},  // PARAM_IFNG_PDL1_HALF
    {"Param.ABM.cell.IFNg_PDL1_n", "", "pr"},  // PARAM_IFNG_PDL1_N
    {"Param.ABM.cell.PDL1_halflife", "", "pr"},  // PARAM_PDL1_HALF
    {"Param.ABM.TCell.lifespanSD", "", "pos"},  // PARAM_TCELL_LIFESPAN_SD
    {"Param.ABM.TCell.IL2_release_time", "", "pos"},  // PARAM_TCELL_IL2_RELEASE_TIME
    {"Param.ABM.TCell.IL2_prolif_th", "", "pos"},  // PARAM_TCELL_IL2_PROLIF_TH
    {"Param.ABM.TCell.IFNg_release_time", "", "pos"},  // PARAM_TCELL_IFNG_RELEASE_TIME
    {"Param.ABM.TCell.IFNg_recruit_Half", "", "pos"},  // PARAM_TEFF_IFN_EC50
    {"Param.ABM.TCell.hypoxia_threshold", "", "pr"},  // PARAM_TCELL_HYPOXIA_TH
    {"Param.ABM.TCell.hypoxia_tier1", "", "pr"},  // PARAM_TCELL_HYPOXIA_TIER1
    {"Param.ABM.TCell.hypoxia_tier2", "", "pr"},  // PARAM_TCELL_HYPOXIA_TIER2
    {"Param.ABM.TCell.hypoxia_recovery", "", "pr"},  // PARAM_TCELL_HYPOXIA_RECOVERY
    {"Param.ABM.TCell.hypoxia_factor1", "", "pr"},  // PARAM_TCELL_HYPOXIA_FACTOR1
    {"Param.ABM.TCell.hypoxia_factor2", "", "pr"},  // PARAM_TCELL_HYPOXIA_FACTOR2
    {"Param.ABM.TCell.hypoxia_factor3", "", "pr"},  // PARAM_TCELL_HYPOXIA_FACTOR3
    {"Param.ABM.TCD4.lifespanSD", "", "pos"},  // PARAM_TCD4_LIFESPAN_SD
    {"Param.ABM.TCD4.TGFB_release_time", "", "pos"},  // PARAM_TCD4_TGFB_RELEASE_TIME
    {"Param.ABM.MDSC.lifespanSD", "", "pos"},  // PARAM_MDSC_LIFESPAN_SD
    {"Param.ABM.Mac.hypoxia_threshold", "", "pr"},  // PARAM_MAC_HYPOXIA_TH
    {"Param.ABM.Mac.m2_bias_strength", "", "pr"},  // PARAM_MAC_M2_BIAS_STRENGTH
    {"Param.ABM.CancerCell.progGrowthRate", "", "pr"},  // PARAM_PROG_GROWTH_RATE
    {"Param.ABM.CancerCell.senescentDeathRate", "", "pr"},  // PARAM_SEN_DEATH_RATE
    {"Param.ABM.CancerCell.asymmetricDivProb", "", "pr"},  // PARAM_ASYM_DIV_PROB
    {"Param.ABM.CancerCell.Tkill_scaler", "", "pos"},  // PARAM_TKILL_SCALAR
    {"Param.ABM.CancerCell.mincc", "", "pos"},  // PARAM_MIN_CC
    {"Param.ABM.CancerCell.C1_CD47", "", "pos"},  // PARAM_C1_CD47
    {"Param.ABM.CancerCell.IFNgUptake", "", "pr"},  // PARAM_CANCER_IFNG_UPTAKE
    {"Param.ABM.CancerCell.hypoxia_th", "", "pr"},  // PARAM_CANCER_HYPOXIA_TH
    {"Param.ABM.CancerCell.hif_vegf_boost", "", "pr"},  // PARAM_HIF_VEGF_BOOST
    {"Param.ABM.CancerCell.hif_ccl2_boost", "", "pr"},  // PARAM_HIF_CCL2_BOOST
    {"Param.ABM.CancerCell.hif_pdl1_boost", "", "pr"},  // PARAM_HIF_PDL1_BOOST
    {"Param.ABM.CancerCell.hif_mhc_reduction", "", "pr"},  // PARAM_HIF_MHC_REDUCTION
    {"Param.ABM.CancerCell.density_csc", "", "pr"},  // PARAM_DENSITY_STEM
    {"Param.ABM.Vas.maxPerVoxel", "", "pos"},  // PARAM_VAS_MAXPERVOXEL
    {"Param.ABM.Vas.vas_50", "", "pr"},  // PARAM_VAS_50
    {"Param.ABM.Vas.O2_conc", "", "pr"},  // PARAM_VAS_O2_CONC
    {"Param.ABM.Vas.Rc", "", "pr"},  // PARAM_VAS_RC
    {"Param.ABM.Vas.sigma", "", "pr"},  // PARAM_VAS_SIGMA
    {"Param.ABM.Vas.ref_vas_frac", "", "pr"},  // PARAM_VAS_FRAC
    {"Param.ABM.Vas.init_density", "", "pr"},  // PARAM_VAS_INIT_DENS
    {"Param.ABM.Vas.tumble", "", "pr"},  // PARAM_VAS_TUMBLE
    {"Param.ABM.Vas.delta", "", "pr"},  // PARAM_VAS_DELTA
    {"Param.ABM.Vas.branch_prob", "", "pr"},  // PARAM_VAS_BRANCH_PROB
    {"Param.ABM.Vas.min_neighbor", "", "pos"},  // PARAM_VAS_MIN_NEIGHBOR
    {"Param.ABM.Vas.maturity_resistance", "", "pr"},  // PARAM_VAS_MATURITY_RESISTANCE
    {"Param.ABM.Vas.initial_maturity", "", "pr"},  // PARAM_VAS_INITIAL_MATURITY
    {"Param.ABM.Vas.collapse_threshold", "", "pr"},  // PARAM_VAS_COLLAPSE_THRESHOLD
    {"Param.ABM.Vas.collapse_ec50", "", "pr"},  // PARAM_VAS_COLLAPSE_EC50
    {"Param.ABM.Vas.recovery_threshold", "", "pr"},  // PARAM_VAS_RECOVERY_THRESHOLD
    {"Param.ABM.Vas.recovery_rate", "", "pr"},  // PARAM_VAS_RECOVERY_RATE
    {"Param.ABM.Vas.regress_rate", "", "pr"},  // PARAM_VAS_REGRESS_RATE
    {"Param.ABM.Vas.vegfa_survival_ec50", "", "pr"},  // PARAM_VAS_VEGFA_SURVIVAL_EC50
    {"Param.ABM.Vas.kvl_dysfunctional", "", "pr"},  // PARAM_VAS_KVL_DYSFUNCTIONAL
    {"Param.ABM.Vas.hypoxia_threshold", "", "pr"},  // PARAM_VAS_HYPOXIA_TH
    {"Param.ABM.Fib.myCAF_TGFB_EC50", "", "pr"},  // PARAM_FIB_MYCAF_TGFB_EC50
    {"Param.ABM.Fib.myCAF_TGFB_hill_n", "", "pr"},  // PARAM_FIB_MYCAF_TGFB_HILL_N
    {"Param.ABM.Fib.iCAF_IL1_EC50", "", "pr"},  // PARAM_FIB_ICAF_IL1_EC50
    {"Param.ABM.Fib.iCAF_IL1_hill_n", "", "pr"},  // PARAM_FIB_ICAF_IL1_HILL_N
    {"Param.ABM.Fib.iCAF_TGFB_suppress_EC50", "", "pr"},  // PARAM_FIB_ICAF_TGFB_SUPPRESS_EC50
    {"Param.ABM.Fib.iCAF_TGFB_suppress_n", "", "pr"},  // PARAM_FIB_ICAF_TGFB_SUPPRESS_N
    {"Param.ABM.Fib.activation_rate", "", "pr"},  // PARAM_FIB_ACTIVATION_RATE
    {"Param.ABM.Fib.move_prob_quiescent", "", "pr"},  // PARAM_FIB_MOVE_PROB_QUIESCENT
    {"Param.ABM.Fib.move_prob_myCAF", "", "pr"},  // PARAM_FIB_MOVE_PROB_MYCAF
    {"Param.ABM.Fib.move_prob_iCAF", "", "pr"},  // PARAM_FIB_MOVE_PROB_ICAF
    {"Param.ABM.Fib.myCAF_TGFB_release", "", "pr"},  // PARAM_FIB_MYCAF_TGFB_RELEASE
    {"Param.ABM.Fib.myCAF_CCL2_release", "", "pr"},  // PARAM_FIB_MYCAF_CCL2_RELEASE
    {"Param.ABM.Fib.iCAF_IL6_release", "", "pr"},  // PARAM_FIB_ICAF_IL6_RELEASE
    {"Param.ABM.Fib.iCAF_CXCL13_release", "", "pr"},  // PARAM_FIB_ICAF_CXCL13_RELEASE
    {"Param.ABM.Fib.iCAF_CCL2_release", "", "pr"},  // PARAM_FIB_ICAF_CCL2_RELEASE
    {"Param.ABM.Fib.ECM_radius", "", "pr"},  // PARAM_FIB_ECM_RADIUS
    {"Param.ABM.Fib.ECM_variance", "", "pr"},  // PARAM_FIB_ECM_VARIANCE
    {"Param.ABM.Fib.div_prob", "", "pr"},  // PARAM_FIB_DIV_PROB
    {"Param.ABM.Fib.div_cooldown", "", "pr"},  // PARAM_FIB_DIV_COOLDOWN
    {"Param.ABM.Fib.div_max", "", "pr"},  // PARAM_FIB_DIV_MAX
    {"Param.ABM.Fib.hypoxia_th", "mM", "pr"},  // PARAM_FIB_HYPOXIA_TH
    {"Param.ABM.Fib.hif_tgfb_boost", "", "pr"},  // PARAM_FIB_HIF_TGFB_BOOST
    {"Param.ABM.Fib.hif_ecm_boost", "", "pr"},  // PARAM_FIB_HIF_ECM_BOOST
    {"Param.ABM.Occupancy.voxelCapacity", "um3", "pr"},  // PARAM_VOXEL_CAPACITY
    {"Param.ABM.Occupancy.CancerCell.stemVolume", "um3", "pr"},  // PARAM_VOLUME_CANCER_STEM
    {"Param.ABM.Occupancy.CancerCell.progenitorVolume", "um3", "pr"},  // PARAM_VOLUME_CANCER_PROG
    {"Param.ABM.Occupancy.CancerCell.senescentVolume", "um3", "pr"},  // PARAM_VOLUME_CANCER_SEN
    {"Param.ABM.Occupancy.TCell.effectorVolume", "um3", "pr"},  // PARAM_VOLUME_TCELL_EFF
    {"Param.ABM.Occupancy.TCell.cytotoxicVolume", "um3", "pr"},  // PARAM_VOLUME_TCELL_CYT
    {"Param.ABM.Occupancy.TCell.suppressedVolume", "um3", "pr"},  // PARAM_VOLUME_TCELL_SUP
    {"Param.ABM.Occupancy.TReg.regulatoryVolume", "um3", "pr"},  // PARAM_VOLUME_TREG_REG
    {"Param.ABM.Occupancy.TReg.helperVolume", "um3", "pr"},  // PARAM_VOLUME_TREG_TH
    {"Param.ABM.Occupancy.Mac.m1Volume", "um3", "pr"},  // PARAM_VOLUME_MAC_M1
    {"Param.ABM.Occupancy.Mac.m2Volume", "um3", "pr"},  // PARAM_VOLUME_MAC_M2
    {"Param.ABM.Occupancy.Fib.quiescentVolume", "um3", "pr"},  // PARAM_VOLUME_FIB_QUIESCENT
    {"Param.ABM.Occupancy.Fib.myCAFVolume", "um3", "pr"},  // PARAM_VOLUME_FIB_MYCAF
    {"Param.ABM.Occupancy.Fib.iCAFVolume", "um3", "pr"},  // PARAM_VOLUME_FIB_ICAF
    {"Param.ABM.Occupancy.MDSC.volume", "um3", "pr"},  // PARAM_VOLUME_MDSC
    {"Param.ABM.Occupancy.Vas.phalanxVolume", "um3", "pr"},  // PARAM_VOLUME_VAS_PHALANX
    {"Param.ABM.Occupancy.Vas.tipVolume", "um3", "pr"},  // PARAM_VOLUME_VAS_TIP
    {"Param.ABM.ECM.depositionRate", "", "pr"},  // PARAM_ECM_DEPOSITION_RATE
    {"Param.ABM.ECM.densityCap", "", "pr"},  // PARAM_ECM_DENSITY_CAP
    {"Param.ABM.ECM.mmpDegradeRate", "", "pr"},  // PARAM_ECM_MMP_DEGRADE_RATE
    {"Param.ABM.ECM.crosslinkRate", "", "pr"},  // PARAM_ECM_CROSSLINK_RATE
    {"Param.ABM.ECM.crosslinkResistance", "", "pr"},  // PARAM_ECM_CROSSLINK_RESISTANCE
    {"Param.ABM.ECM.decayRate", "", "pr"},  // PARAM_ECM_DECAY_RATE
    {"Param.ABM.ECM.baseline", "", "pr"},  // PARAM_ECM_BASELINE
    {"Param.ABM.ECM.tgfbEC50", "", "pr"},  // PARAM_ECM_TGFB_EC50
    {"Param.ABM.ECM.porosityCancer", "", "pr"},  // PARAM_ECM_POROSITY_CANCER
    {"Param.ABM.ECM.porosityTcell", "", "pr"},  // PARAM_ECM_POROSITY_TCELL
    {"Param.ABM.ECM.porosityTreg", "", "pr"},  // PARAM_ECM_POROSITY_TREG
    {"Param.ABM.ECM.porosityMDSC", "", "pr"},  // PARAM_ECM_POROSITY_MDSC
    {"Param.ABM.ECM.porosityMac", "", "pr"},  // PARAM_ECM_POROSITY_MAC
    {"Param.ABM.ECM.porosityFib", "", "pr"},  // PARAM_ECM_POROSITY_FIB
    {"Param.ABM.ECM.porosityVasTip", "", "pr"},  // PARAM_ECM_POROSITY_VAS_TIP
    {"Param.ABM.ECM.vasCompressK", "", "pr"},  // PARAM_VAS_ECM_COMPRESS_K
    {"Param.ABM.ECM.yapEC50", "", "pr"},  // PARAM_ECM_YAP_EC50
    {"Param.ABM.DomainInit.lobule_spacing", "voxels", "pr"},  // PARAM_DOMAIN_LOBULE_SPACING
    {"Param.ABM.DomainInit.septum_thickness", "voxels", "pr"},  // PARAM_DOMAIN_SEPTUM_THICKNESS
    {"Param.ABM.DomainInit.tumor_radius_fraction", "", "pr"},  // PARAM_DOMAIN_TUMOR_RADIUS_FRAC
    {"Param.ABM.DomainInit.margin_thickness", "voxels", "pr"},  // PARAM_DOMAIN_MARGIN_THICKNESS
    {"Param.ABM.DomainInit.ecm_septum_density", "", "pr"},  // PARAM_DOMAIN_ECM_SEPTUM_DENSITY
    {"Param.ABM.DomainInit.ecm_septum_crosslink", "", "pr"},  // PARAM_DOMAIN_ECM_SEPTUM_CROSSLINK
    {"Param.ABM.DomainInit.ecm_stroma_density", "", "pr"},  // PARAM_DOMAIN_ECM_STROMA_DENSITY
    {"Param.ABM.DomainInit.ecm_lobule_density", "", "pr"},  // PARAM_DOMAIN_ECM_LOBULE_DENSITY
    {"Param.ABM.DomainInit.ecm_margin_density", "", "pr"},  // PARAM_DOMAIN_ECM_MARGIN_DENSITY
    {"Param.ABM.DomainInit.ecm_margin_crosslink", "", "pr"},  // PARAM_DOMAIN_ECM_MARGIN_CROSSLINK
    {"Param.ABM.DomainInit.ecm_tumor_density", "", "pr"},  // PARAM_DOMAIN_ECM_TUMOR_DENSITY
    {"Param.ABM.DomainInit.Fibroblast.p_septum", "", "pr"},  // PARAM_DOMAIN_FIB_P_SEPTUM
    {"Param.ABM.DomainInit.Fibroblast.p_stroma", "", "pr"},  // PARAM_DOMAIN_FIB_P_STROMA
    {"Param.ABM.DomainInit.Fibroblast.p_lobule", "", "pr"},  // PARAM_DOMAIN_FIB_P_LOBULE
    {"Param.ABM.DomainInit.Fibroblast.p_margin", "", "pr"},  // PARAM_DOMAIN_FIB_P_MARGIN
    {"Param.ABM.DomainInit.Fibroblast.p_tumor", "", "pr"},  // PARAM_DOMAIN_FIB_P_TUMOR
    {"Param.ABM.DomainInit.Fibroblast.margin_mycaf_fraction", "", "pr"},  // PARAM_DOMAIN_FIB_MARGIN_MYCAF_FRAC
    {"Param.ABM.DomainInit.Vascular.p_septum", "", "pr"},  // PARAM_DOMAIN_VAS_P_SEPTUM
    {"Param.ABM.DomainInit.Vascular.p_stroma", "", "pr"},  // PARAM_DOMAIN_VAS_P_STROMA
    {"Param.ABM.DomainInit.Vascular.p_lobule", "", "pr"},  // PARAM_DOMAIN_VAS_P_LOBULE
    {"Param.ABM.DomainInit.Vascular.p_margin", "", "pr"},  // PARAM_DOMAIN_VAS_P_MARGIN
    {"Param.ABM.DomainInit.Vascular.p_tumor", "", "pr"},  // PARAM_DOMAIN_VAS_P_TUMOR
    {"Param.ABM.DomainInit.Vascular.margin_tip_fraction", "", "pr"},  // PARAM_DOMAIN_VAS_MARGIN_TIP_FRAC
    {"Param.ABM.DomainInit.Macrophage.p_stroma", "", "pr"},  // PARAM_DOMAIN_MAC_P_STROMA
    {"Param.ABM.DomainInit.Macrophage.p_margin", "", "pr"},  // PARAM_DOMAIN_MAC_P_MARGIN
    {"Param.ABM.DomainInit.Macrophage.p_tumor", "", "pr"},  // PARAM_DOMAIN_MAC_P_TUMOR
    {"Param.ABM.DomainInit.Macrophage.margin_m1_fraction", "", "pr"},  // PARAM_DOMAIN_MAC_MARGIN_M1_FRAC
    {"Param.ABM.DomainInit.TH.p_stroma", "", "pr"},  // PARAM_DOMAIN_TH_P_STROMA
    {"Param.ABM.Movement.Persistence.tcell_eff", "", "pr"},  // PARAM_PERSIST_TCELL_EFF
    {"Param.ABM.Movement.Persistence.tcell_cyt", "", "pr"},  // PARAM_PERSIST_TCELL_CYT
    {"Param.ABM.Movement.Persistence.tcell_sup", "", "pr"},  // PARAM_PERSIST_TCELL_SUP
    {"Param.ABM.Movement.Persistence.mac_m1", "", "pr"},  // PARAM_PERSIST_MAC_M1
    {"Param.ABM.Movement.Persistence.mac_m2", "", "pr"},  // PARAM_PERSIST_MAC_M2
    {"Param.ABM.Movement.Persistence.fib_mycaf", "", "pr"},  // PARAM_PERSIST_FIB_MYCAF
    {"Param.ABM.Movement.Persistence.fib_icaf", "", "pr"},  // PARAM_PERSIST_FIB_ICAF
    {"Param.ABM.Movement.Persistence.vas_tip", "", "pr"},  // PARAM_PERSIST_VAS_TIP
    {"Param.ABM.Movement.Persistence.treg_reg", "", "pr"},  // PARAM_PERSIST_TREG_REG
    {"Param.ABM.Movement.Persistence.treg_th", "", "pr"},  // PARAM_PERSIST_TREG_TH
    {"Param.ABM.Movement.Persistence.mdsc", "", "pr"},  // PARAM_PERSIST_MDSC
    {"Param.ABM.Movement.Chemotaxis.cancer_stem_bias", "", "pr"},  // PARAM_CHEMO_BIAS_CANCER_STEM
    {"Param.ABM.Movement.Chemotaxis.mac_m1_bias", "", "pr"},  // PARAM_CHEMO_BIAS_MAC_M1
    {"Param.ABM.Movement.Chemotaxis.mac_m2_bias", "", "pr"},  // PARAM_CHEMO_BIAS_MAC_M2
    {"Param.ABM.Movement.Chemotaxis.fib_mycaf_bias", "", "pr"},  // PARAM_CHEMO_BIAS_FIB_MYCAF
    {"Param.ABM.Movement.Chemotaxis.vas_tip_bias", "", "pr"},  // PARAM_CHEMO_BIAS_VAS_TIP
    {"Param.ABM.Movement.Chemotaxis.treg_reg_bias", "", "pr"},  // PARAM_CHEMO_BIAS_TREG_REG
    {"Param.ABM.Movement.Chemotaxis.mdsc_bias", "", "pr"},  // PARAM_CHEMO_BIAS_MDSC
    {"Param.ABM.Movement.Adhesion.ecm_density_threshold", "", "pr"},  // PARAM_ADH_ECM_DENSITY_TH
    {"Param.ABM.Movement.Adhesion.cancer_stem_to_cancer", "", "pr"},  // PARAM_ADH_CANCER_STEM_CANCER
    {"Param.ABM.Movement.Adhesion.cancer_stem_to_fib", "", "pr"},  // PARAM_ADH_CANCER_STEM_FIB
    {"Param.ABM.Movement.Adhesion.cancer_stem_to_ecm", "", "pr"},  // PARAM_ADH_CANCER_STEM_ECM
    {"Param.ABM.Movement.Adhesion.cancer_prog_to_cancer", "", "pr"},  // PARAM_ADH_CANCER_PROG_CANCER
    {"Param.ABM.Movement.Adhesion.cancer_prog_to_fib", "", "pr"},  // PARAM_ADH_CANCER_PROG_FIB
    {"Param.ABM.Movement.Adhesion.cancer_prog_to_ecm", "", "pr"},  // PARAM_ADH_CANCER_PROG_ECM
    {"Param.ABM.Movement.Adhesion.tcell_cyt_to_cancer", "", "pr"},  // PARAM_ADH_TCELL_CYT_CANCER
    {"Param.ABM.Movement.Adhesion.mac_m2_to_cancer", "", "pr"},  // PARAM_ADH_MAC_M2_CANCER
    {"Param.ABM.Movement.Adhesion.mac_m2_to_fib", "", "pr"},  // PARAM_ADH_MAC_M2_FIB
    {"Param.ABM.Movement.Adhesion.mac_m2_to_ecm", "", "pr"},  // PARAM_ADH_MAC_M2_ECM
    {"Param.ABM.Movement.Adhesion.fib_mycaf_to_cancer", "", "pr"},  // PARAM_ADH_FIB_MYCAF_CANCER
    {"Param.ABM.Movement.Adhesion.fib_mycaf_to_fib", "", "pr"},  // PARAM_ADH_FIB_MYCAF_FIB
    {"Param.ABM.Movement.Adhesion.fib_mycaf_to_ecm", "", "pr"},  // PARAM_ADH_FIB_MYCAF_ECM
    {"Param.ABM.Movement.Adhesion.fib_icaf_to_cancer", "", "pr"},  // PARAM_ADH_FIB_ICAF_CANCER
    {"Param.ABM.Movement.Adhesion.fib_icaf_to_fib", "", "pr"},  // PARAM_ADH_FIB_ICAF_FIB
    {"Param.ABM.Movement.Adhesion.fib_icaf_to_ecm", "", "pr"},  // PARAM_ADH_FIB_ICAF_ECM
    {"Param.Molecular.biofvm.IFNg.diffusivity", "", "pr"},  // PARAM_IFNG_DIFFUSIVITY
    {"Param.Molecular.biofvm.IFNg.release", "", "pr"},  // PARAM_IFNG_RELEASE
    {"Param.Molecular.biofvm.IFNg.decayRate", "", "pr"},  // PARAM_IFNG_DECAY_RATE
    {"Param.Molecular.biofvm.IFNg.molecularWeight", "", "pr"},  // PARAM_IFNG_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.IL_2.diffusivity", "", "pr"},  // PARAM_IL2_DIFFUSIVITY
    {"Param.Molecular.biofvm.IL_2.release", "", "pr"},  // PARAM_IL2_RELEASE
    {"Param.Molecular.biofvm.IL_2.uptake", "", "pr"},  // PARAM_IL2_UPTAKE
    {"Param.Molecular.biofvm.IL_2.decayRate", "", "pr"},  // PARAM_IL2_DECAY_RATE
    {"Param.Molecular.biofvm.IL_2.molecularWeight", "", "pr"},  // PARAM_IL2_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.CCL2.diffusivity", "", "pr"},  // PARAM_CCL2_DIFFUSIVITY
    {"Param.Molecular.biofvm.CCL2.release", "", "pr"},  // PARAM_CCL2_RELEASE
    {"Param.Molecular.biofvm.CCL2.uptake", "", "pr"},  // PARAM_CCL2_UPTAKE
    {"Param.Molecular.biofvm.CCL2.decayRate", "", "pr"},  // PARAM_CCL2_DECAY_RATE
    {"Param.Molecular.biofvm.CCL2.molecularWeight", "", "pr"},  // PARAM_CCL2_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.ArgI.diffusivity", "", "pr"},  // PARAM_ARGI_DIFFUSIVITY
    {"Param.Molecular.biofvm.ArgI.release", "", "pr"},  // PARAM_ARGI_RELEASE
    {"Param.Molecular.biofvm.ArgI.decayRate", "", "pr"},  // PARAM_ARGI_DECAY_RATE
    {"Param.Molecular.biofvm.ArgI.molecularWeight", "", "pr"},  // PARAM_ARGI_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.NO.diffusivity", "", "pr"},  // PARAM_NO_DIFFUSIVITY
    {"Param.Molecular.biofvm.NO.release", "", "pr"},  // PARAM_NO_RELEASE
    {"Param.Molecular.biofvm.NO.decayRate", "", "pr"},  // PARAM_NO_DECAY_RATE
    {"Param.Molecular.biofvm.NO.molecularWeight", "", "pr"},  // PARAM_NO_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.TGFB.diffusivity", "", "pr"},  // PARAM_TGFB_DIFFUSIVITY
    {"Param.Molecular.biofvm.TGFB.release.Treg", "", "pr"},  // PARAM_TREG_TGFB_RELEASE
    {"Param.Molecular.biofvm.TGFB.release.Mac", "", "pr"},  // PARAM_MAC_TGFB_RELEASE
    {"Param.Molecular.biofvm.TGFB.release.CancerStem", "", "pr"},  // PARAM_STEM_TGFB_RELEASE
    {"Param.Molecular.biofvm.TGFB.release.CancerProgenitor", "", "pr"},  // PARAM_PROG_TGFB_RELEASE
    {"Param.Molecular.biofvm.TGFB.decayRate", "", "pr"},  // PARAM_TGFB_DECAY_RATE
    {"Param.Molecular.biofvm.TGFB.molecularWeight", "", "pr"},  // PARAM_TGFB_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.IL10.diffusivity", "", "pr"},  // PARAM_IL10_DIFFUSIVITY
    {"Param.Molecular.biofvm.IL10.release.Treg", "", "pr"},  // PARAM_TREG_IL10_RELEASE
    {"Param.Molecular.biofvm.IL10.release.Mac", "", "pr"},  // PARAM_MAC_IL10_RELEASE
    {"Param.Molecular.biofvm.IL10.decayRate", "", "pr"},  // PARAM_IL10_DECAY_RATE
    {"Param.Molecular.biofvm.IL10.molecularWeight", "", "pr"},  // PARAM_IL10_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.IL12.diffusivity", "", "pr"},  // PARAM_IL12_DIFFUSIVITY
    {"Param.Molecular.biofvm.IL12.release", "", "pr"},  // PARAM_IL12_RELEASE
    {"Param.Molecular.biofvm.IL12.decayRate", "", "pr"},  // PARAM_IL12_DECAY_RATE
    {"Param.Molecular.biofvm.IL12.molecularWeight", "", "pr"},  // PARAM_IL12_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.VEGFA.diffusivity", "", "pr"},  // PARAM_VEGFA_DIFFUSIVITY
    {"Param.Molecular.biofvm.VEGFA.release.Mac", "", "pr"},  // PARAM_MAC_VEGFA_RELEASE
    {"Param.Molecular.biofvm.VEGFA.release.CancerStem", "", "pr"},  // PARAM_STEM_VEGFA_RELEASE
    {"Param.Molecular.biofvm.VEGFA.release.CancerProgenitor", "", "pr"},  // PARAM_PROG_VEGFA_RELEASE
    {"Param.Molecular.biofvm.VEGFA.uptake", "", "pr"},  // PARAM_VEGFA_UPTAKE
    {"Param.Molecular.biofvm.VEGFA.decayRate", "", "pr"},  // PARAM_VEGFA_DECAY_RATE
    {"Param.Molecular.biofvm.VEGFA.molecularWeight", "", "pr"},  // PARAM_VEGFA_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.O2.diffusivity", "", "pr"},  // PARAM_O2_DIFFUSIVITY
    {"Param.Molecular.biofvm.O2.uptake", "", "pr"},  // PARAM_O2_UPTAKE
    {"Param.Molecular.biofvm.O2.decayRate", "", "pr"},  // PARAM_O2_DECAY_RATE
    {"Param.Molecular.biofvm.O2.molecularWeight", "", "pr"},  // PARAM_O2_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.IL1.diffusivity", "", "pr"},  // PARAM_IL1_DIFFUSIVITY
    {"Param.Molecular.biofvm.IL1.release.CancerStem", "", "pr"},  // PARAM_CANCER_IL1_RELEASE_STEM
    {"Param.Molecular.biofvm.IL1.release.CancerProg", "", "pr"},  // PARAM_CANCER_IL1_RELEASE_PROG
    {"Param.Molecular.biofvm.IL1.release.CancerSen", "", "pr"},  // PARAM_CANCER_IL1_RELEASE_SEN
    {"Param.Molecular.biofvm.IL1.release.MacM1", "", "pr"},  // PARAM_MAC_M1_IL1_RELEASE
    {"Param.Molecular.biofvm.IL1.decayRate", "", "pr"},  // PARAM_IL1_DECAY_RATE
    {"Param.Molecular.biofvm.IL1.molecularWeight", "", "pr"},  // PARAM_IL1_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.IL6.diffusivity", "", "pr"},  // PARAM_IL6_DIFFUSIVITY
    {"Param.Molecular.biofvm.IL6.decayRate", "", "pr"},  // PARAM_IL6_DECAY_RATE
    {"Param.Molecular.biofvm.IL6.molecularWeight", "", "pr"},  // PARAM_IL6_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.CXCL13.diffusivity", "", "pr"},  // PARAM_CXCL13_DIFFUSIVITY
    {"Param.Molecular.biofvm.CXCL13.decayRate", "", "pr"},  // PARAM_CXCL13_DECAY_RATE
    {"Param.Molecular.biofvm.CXCL13.molecularWeight", "", "pr"},  // PARAM_CXCL13_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.MMP.diffusivity", "", "pr"},  // PARAM_MMP_DIFFUSIVITY
    {"Param.Molecular.biofvm.MMP.decayRate", "", "pr"},  // PARAM_MMP_DECAY_RATE
    {"Param.Molecular.biofvm.MMP.molecularWeight", "", "pr"},  // PARAM_MMP_MOLECULAR_WEIGHT
    {"Param.Molecular.biofvm.MMP.release.Cancer", "", "pr"},  // PARAM_CANCER_MMP_RELEASE
    {"Param.Molecular.biofvm.MMP.release.MacM1", "", "pr"},  // PARAM_MAC_M1_MMP_RELEASE
    {"Param.QSP.simulation.weight_qsp", "", "pr"},  // PARAM_WEIGHT_QSP
    // Int parameters
    {"Param.ABM.Environment.ShuffleInterval", "slices", "pos"},  // PARAM_SHUFFLE_INTERVAL
    {"Param.ABM.Environment.gridshiftInterval", "slices", "pos"},  // PARAM_GRID_SHIFT_INTERVAL
    {"Param.ABM.Environment.Tumor.XSize", "microns", "pos"},  // PARAM_X_SIZE
    {"Param.ABM.Environment.Tumor.YSize", "microns", "pos"},  // PARAM_Y_SIZE
    {"Param.ABM.Environment.Tumor.ZSize", "microns", "pos"},  // PARAM_Z_SIZE
    {"Param.ABM.Environment.Tumor.VoxelSize", "microns", "pos"},  // PARAM_VOXEL_SIZE
    {"Param.ABM.Environment.Tumor.nr_T_voxel", "", "pos"},  // PARAM_NR_T_VOXELS
    {"Param.ABM.Environment.Tumor.nr_T_voxel_C", "", "pos"},  // PARAM_NR_T_VOXELS_C
    {"Param.ABM.Environment.Tumor.stem_mode", "", "pos"},  // PARAM_STEM_MODE
    {"Param.ABM.TCell.div_interval", "", "pos"},  // PARAM_TCELL_DIV_INTERNAL
    {"Param.ABM.TCell.div_limit", "", "pos"},  // PARAM_TCELL_DIV_LIMIT
    {"Param.ABM.TCell.moveSteps", "", "pos"},  // PARAM_TCELL_MOVE_STEPS
    {"Param.ABM.TCD4.div_interval", "", "pos"},  // PARAM_TCD4_DIV_INTERNAL
    {"Param.ABM.TCD4.div_limit", "", "pos"},  // PARAM_TCD4_DIV_LIMIT
    {"Param.ABM.MDSC.moveSteps", "", "pos"},  // PARAM_MDSC_MOVE_STEPS
    {"Param.ABM.Mac.moveSteps", "", "pos"},  // PARAM_MAC_MOVE_STEPS
    {"Param.ABM.CancerCell.progenitorDivMax", "", "pos"},  // PARAM_PROG_DIV_MAX
    {"Param.ABM.CancerCell.moveSteps", "", "pos"},  // PARAM_CANCER_MOVE_STEPS
    {"Param.ABM.CancerCell.moveSteps_csc", "", "pos"},  // PARAM_CANCER_MOVE_STEPS_STEM
    {"Param.ABM.Fib.moveSteps", "", "pos"},  // PARAM_FIB_MOVE_STEPS
    {"Param.ABM.DomainInit.pde_warmup_substeps", "", "pos"},  // PARAM_DOMAIN_PDE_WARMUP_SUBSTEPS
    {"Param.Molecular.stepPerSlice", "", "pos"},  // PARAM_MOLECULAR_STEPS
    // Bool parameters
    {"Param.ABM.Pharmacokinetics.nivoOn", "", ""},  // PARAM_NIVO_ON
    {"Param.ABM.Pharmacokinetics.ipiOn", "", ""},  // PARAM_IPI_ON
    {"Param.ABM.Pharmacokinetics.caboOn", "", ""},  // PARAM_CABO_ON
    {"Param.ABM.Pharmacokinetics.entOn", "", ""},  // PARAM_ENT_ON
};

// Verify that _gpu_param_description has the correct number of entries
static_assert(sizeof(_gpu_param_description) / sizeof(_gpu_param_description[0]) == 
        static_cast<int>(GPU_PARAM_FLOAT_COUNT)+static_cast<int>(GPU_PARAM_INT_COUNT)+static_cast<int>(GPU_PARAM_BOOL_COUNT),
        "GPU parameter description array size mismatch");

GPUParam::GPUParam() : ParamBase() {
    setupParam();
}

void GPUParam::setupParam() {
    _paramFloat.resize(GPU_PARAM_FLOAT_COUNT, 0.0);
    _paramInt.resize(GPU_PARAM_INT_COUNT, 0);
    _paramBool.resize(GPU_PARAM_BOOL_COUNT, false);

    for (size_t i = 0; i < static_cast<int>(GPU_PARAM_FLOAT_COUNT)+
                                static_cast<int>(GPU_PARAM_INT_COUNT)+
                                static_cast<int>(GPU_PARAM_BOOL_COUNT); i++) {
        std::vector<std::string> desc(
            _gpu_param_description[i],
            _gpu_param_description[i] + 3);
        _paramDesc.push_back(desc);
    }
}

void GPUParam::processInternalParams() {
    // ParamBase handles validation based on the "pr" and "pos" tags
}

void GPUParam::populateFlameGPUEnvironment(flamegpu::EnvironmentDescription& env) const {
    env.newProperty<float>("PARAM_SEC_PER_SLICE", getFloat(PARAM_SEC_PER_SLICE));
    env.newProperty<float>("PARAM_REC_SITE_FACTOR", getFloat(PARAM_REC_SITE_FACTOR));
    env.newProperty<float>("PARAM_ADH_SITE_DENSITY", getFloat(PARAM_ADH_SITE_DENSITY));
    env.newProperty<float>("PARAM_NIVO_DOSE_INTERVAL_TIME", getFloat(PARAM_NIVO_DOSE_INTERVAL_TIME));
    env.newProperty<float>("PARAM_NIVO_DOSE", getFloat(PARAM_NIVO_DOSE));
    env.newProperty<float>("PARAM_IPI_DOSE_INTERVAL_TIME", getFloat(PARAM_IPI_DOSE_INTERVAL_TIME));
    env.newProperty<float>("PARAM_IPI_DOSE", getFloat(PARAM_IPI_DOSE));
    env.newProperty<float>("PARAM_CABO_DOSE_INTERVAL_TIME", getFloat(PARAM_CABO_DOSE_INTERVAL_TIME));
    env.newProperty<float>("PARAM_CABO_DOSE", getFloat(PARAM_CABO_DOSE));
    env.newProperty<float>("PARAM_PDL1_TH", getFloat(PARAM_PDL1_TH));
    env.newProperty<float>("PARAM_IFNG_PDL1_HALF", getFloat(PARAM_IFNG_PDL1_HALF));
    env.newProperty<float>("PARAM_IFNG_PDL1_N", getFloat(PARAM_IFNG_PDL1_N));
    env.newProperty<float>("PARAM_PDL1_HALF", getFloat(PARAM_PDL1_HALF));
    env.newProperty<float>("PARAM_TCELL_LIFESPAN_SD", getFloat(PARAM_TCELL_LIFESPAN_SD));
    env.newProperty<float>("PARAM_TCELL_IL2_RELEASE_TIME", getFloat(PARAM_TCELL_IL2_RELEASE_TIME));
    env.newProperty<float>("PARAM_TCELL_IL2_PROLIF_TH", getFloat(PARAM_TCELL_IL2_PROLIF_TH));
    env.newProperty<float>("PARAM_TCELL_IFNG_RELEASE_TIME", getFloat(PARAM_TCELL_IFNG_RELEASE_TIME));
    env.newProperty<float>("PARAM_TEFF_IFN_EC50", getFloat(PARAM_TEFF_IFN_EC50));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_TH", getFloat(PARAM_TCELL_HYPOXIA_TH));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_TIER1", getFloat(PARAM_TCELL_HYPOXIA_TIER1));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_TIER2", getFloat(PARAM_TCELL_HYPOXIA_TIER2));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_RECOVERY", getFloat(PARAM_TCELL_HYPOXIA_RECOVERY));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_FACTOR1", getFloat(PARAM_TCELL_HYPOXIA_FACTOR1));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_FACTOR2", getFloat(PARAM_TCELL_HYPOXIA_FACTOR2));
    env.newProperty<float>("PARAM_TCELL_HYPOXIA_FACTOR3", getFloat(PARAM_TCELL_HYPOXIA_FACTOR3));
    env.newProperty<float>("PARAM_TCD4_LIFESPAN_SD", getFloat(PARAM_TCD4_LIFESPAN_SD));
    env.newProperty<float>("PARAM_TCD4_TGFB_RELEASE_TIME", getFloat(PARAM_TCD4_TGFB_RELEASE_TIME));
    env.newProperty<float>("PARAM_MDSC_LIFESPAN_SD", getFloat(PARAM_MDSC_LIFESPAN_SD));
    env.newProperty<float>("PARAM_MAC_HYPOXIA_TH", getFloat(PARAM_MAC_HYPOXIA_TH));
    env.newProperty<float>("PARAM_MAC_M2_BIAS_STRENGTH", getFloat(PARAM_MAC_M2_BIAS_STRENGTH));
    env.newProperty<float>("PARAM_PROG_GROWTH_RATE", getFloat(PARAM_PROG_GROWTH_RATE));
    env.newProperty<float>("PARAM_SEN_DEATH_RATE", getFloat(PARAM_SEN_DEATH_RATE));
    env.newProperty<float>("PARAM_ASYM_DIV_PROB", getFloat(PARAM_ASYM_DIV_PROB));
    env.newProperty<float>("PARAM_TKILL_SCALAR", getFloat(PARAM_TKILL_SCALAR));
    env.newProperty<float>("PARAM_MIN_CC", getFloat(PARAM_MIN_CC));
    env.newProperty<float>("PARAM_C1_CD47", getFloat(PARAM_C1_CD47));
    env.newProperty<float>("PARAM_CANCER_IFNG_UPTAKE", getFloat(PARAM_CANCER_IFNG_UPTAKE));
    env.newProperty<float>("PARAM_CANCER_HYPOXIA_TH", getFloat(PARAM_CANCER_HYPOXIA_TH));
    env.newProperty<float>("PARAM_HIF_VEGF_BOOST", getFloat(PARAM_HIF_VEGF_BOOST));
    env.newProperty<float>("PARAM_HIF_CCL2_BOOST", getFloat(PARAM_HIF_CCL2_BOOST));
    env.newProperty<float>("PARAM_HIF_PDL1_BOOST", getFloat(PARAM_HIF_PDL1_BOOST));
    env.newProperty<float>("PARAM_HIF_MHC_REDUCTION", getFloat(PARAM_HIF_MHC_REDUCTION));
    env.newProperty<float>("PARAM_DENSITY_STEM", getFloat(PARAM_DENSITY_STEM));
    env.newProperty<float>("PARAM_VAS_MAXPERVOXEL", getFloat(PARAM_VAS_MAXPERVOXEL));
    env.newProperty<float>("PARAM_VAS_50", getFloat(PARAM_VAS_50));
    env.newProperty<float>("PARAM_VAS_O2_CONC", getFloat(PARAM_VAS_O2_CONC));
    env.newProperty<float>("PARAM_VAS_RC", getFloat(PARAM_VAS_RC));
    env.newProperty<float>("PARAM_VAS_SIGMA", getFloat(PARAM_VAS_SIGMA));
    env.newProperty<float>("PARAM_VAS_FRAC", getFloat(PARAM_VAS_FRAC));
    env.newProperty<float>("PARAM_VAS_INIT_DENS", getFloat(PARAM_VAS_INIT_DENS));
    env.newProperty<float>("PARAM_VAS_TUMBLE", getFloat(PARAM_VAS_TUMBLE));
    env.newProperty<float>("PARAM_VAS_DELTA", getFloat(PARAM_VAS_DELTA));
    env.newProperty<float>("PARAM_VAS_BRANCH_PROB", getFloat(PARAM_VAS_BRANCH_PROB));
    env.newProperty<float>("PARAM_VAS_MIN_NEIGHBOR", getFloat(PARAM_VAS_MIN_NEIGHBOR));
    env.newProperty<float>("PARAM_VAS_MATURITY_RESISTANCE", getFloat(PARAM_VAS_MATURITY_RESISTANCE));
    env.newProperty<float>("PARAM_VAS_INITIAL_MATURITY", getFloat(PARAM_VAS_INITIAL_MATURITY));
    env.newProperty<float>("PARAM_VAS_COLLAPSE_THRESHOLD", getFloat(PARAM_VAS_COLLAPSE_THRESHOLD));
    env.newProperty<float>("PARAM_VAS_COLLAPSE_EC50", getFloat(PARAM_VAS_COLLAPSE_EC50));
    env.newProperty<float>("PARAM_VAS_RECOVERY_THRESHOLD", getFloat(PARAM_VAS_RECOVERY_THRESHOLD));
    env.newProperty<float>("PARAM_VAS_RECOVERY_RATE", getFloat(PARAM_VAS_RECOVERY_RATE));
    env.newProperty<float>("PARAM_VAS_REGRESS_RATE", getFloat(PARAM_VAS_REGRESS_RATE));
    env.newProperty<float>("PARAM_VAS_VEGFA_SURVIVAL_EC50", getFloat(PARAM_VAS_VEGFA_SURVIVAL_EC50));
    env.newProperty<float>("PARAM_VAS_KVL_DYSFUNCTIONAL", getFloat(PARAM_VAS_KVL_DYSFUNCTIONAL));
    env.newProperty<float>("PARAM_VAS_HYPOXIA_TH", getFloat(PARAM_VAS_HYPOXIA_TH));
    env.newProperty<float>("PARAM_FIB_MYCAF_TGFB_EC50", getFloat(PARAM_FIB_MYCAF_TGFB_EC50));
    env.newProperty<float>("PARAM_FIB_MYCAF_TGFB_HILL_N", getFloat(PARAM_FIB_MYCAF_TGFB_HILL_N));
    env.newProperty<float>("PARAM_FIB_ICAF_IL1_EC50", getFloat(PARAM_FIB_ICAF_IL1_EC50));
    env.newProperty<float>("PARAM_FIB_ICAF_IL1_HILL_N", getFloat(PARAM_FIB_ICAF_IL1_HILL_N));
    env.newProperty<float>("PARAM_FIB_ICAF_TGFB_SUPPRESS_EC50", getFloat(PARAM_FIB_ICAF_TGFB_SUPPRESS_EC50));
    env.newProperty<float>("PARAM_FIB_ICAF_TGFB_SUPPRESS_N", getFloat(PARAM_FIB_ICAF_TGFB_SUPPRESS_N));
    env.newProperty<float>("PARAM_FIB_ACTIVATION_RATE", getFloat(PARAM_FIB_ACTIVATION_RATE));
    env.newProperty<float>("PARAM_FIB_MOVE_PROB_QUIESCENT", getFloat(PARAM_FIB_MOVE_PROB_QUIESCENT));
    env.newProperty<float>("PARAM_FIB_MOVE_PROB_MYCAF", getFloat(PARAM_FIB_MOVE_PROB_MYCAF));
    env.newProperty<float>("PARAM_FIB_MOVE_PROB_ICAF", getFloat(PARAM_FIB_MOVE_PROB_ICAF));
    env.newProperty<float>("PARAM_FIB_MYCAF_TGFB_RELEASE", getFloat(PARAM_FIB_MYCAF_TGFB_RELEASE));
    env.newProperty<float>("PARAM_FIB_MYCAF_CCL2_RELEASE", getFloat(PARAM_FIB_MYCAF_CCL2_RELEASE));
    env.newProperty<float>("PARAM_FIB_ICAF_IL6_RELEASE", getFloat(PARAM_FIB_ICAF_IL6_RELEASE));
    env.newProperty<float>("PARAM_FIB_ICAF_CXCL13_RELEASE", getFloat(PARAM_FIB_ICAF_CXCL13_RELEASE));
    env.newProperty<float>("PARAM_FIB_ICAF_CCL2_RELEASE", getFloat(PARAM_FIB_ICAF_CCL2_RELEASE));
    env.newProperty<float>("PARAM_FIB_ECM_RADIUS", getFloat(PARAM_FIB_ECM_RADIUS));
    env.newProperty<float>("PARAM_FIB_ECM_VARIANCE", getFloat(PARAM_FIB_ECM_VARIANCE));
    env.newProperty<float>("PARAM_FIB_DIV_PROB", getFloat(PARAM_FIB_DIV_PROB));
    env.newProperty<float>("PARAM_FIB_DIV_COOLDOWN", getFloat(PARAM_FIB_DIV_COOLDOWN));
    env.newProperty<float>("PARAM_FIB_DIV_MAX", getFloat(PARAM_FIB_DIV_MAX));
    env.newProperty<float>("PARAM_FIB_HYPOXIA_TH", getFloat(PARAM_FIB_HYPOXIA_TH));
    env.newProperty<float>("PARAM_FIB_HIF_TGFB_BOOST", getFloat(PARAM_FIB_HIF_TGFB_BOOST));
    env.newProperty<float>("PARAM_FIB_HIF_ECM_BOOST", getFloat(PARAM_FIB_HIF_ECM_BOOST));
    env.newProperty<float>("PARAM_VOXEL_CAPACITY", getFloat(PARAM_VOXEL_CAPACITY));
    env.newProperty<float>("PARAM_VOLUME_CANCER_STEM", getFloat(PARAM_VOLUME_CANCER_STEM));
    env.newProperty<float>("PARAM_VOLUME_CANCER_PROG", getFloat(PARAM_VOLUME_CANCER_PROG));
    env.newProperty<float>("PARAM_VOLUME_CANCER_SEN", getFloat(PARAM_VOLUME_CANCER_SEN));
    env.newProperty<float>("PARAM_VOLUME_TCELL_EFF", getFloat(PARAM_VOLUME_TCELL_EFF));
    env.newProperty<float>("PARAM_VOLUME_TCELL_CYT", getFloat(PARAM_VOLUME_TCELL_CYT));
    env.newProperty<float>("PARAM_VOLUME_TCELL_SUP", getFloat(PARAM_VOLUME_TCELL_SUP));
    env.newProperty<float>("PARAM_VOLUME_TREG_REG", getFloat(PARAM_VOLUME_TREG_REG));
    env.newProperty<float>("PARAM_VOLUME_TREG_TH", getFloat(PARAM_VOLUME_TREG_TH));
    env.newProperty<float>("PARAM_VOLUME_MAC_M1", getFloat(PARAM_VOLUME_MAC_M1));
    env.newProperty<float>("PARAM_VOLUME_MAC_M2", getFloat(PARAM_VOLUME_MAC_M2));
    env.newProperty<float>("PARAM_VOLUME_FIB_QUIESCENT", getFloat(PARAM_VOLUME_FIB_QUIESCENT));
    env.newProperty<float>("PARAM_VOLUME_FIB_MYCAF", getFloat(PARAM_VOLUME_FIB_MYCAF));
    env.newProperty<float>("PARAM_VOLUME_FIB_ICAF", getFloat(PARAM_VOLUME_FIB_ICAF));
    env.newProperty<float>("PARAM_VOLUME_MDSC", getFloat(PARAM_VOLUME_MDSC));
    env.newProperty<float>("PARAM_VOLUME_VAS_PHALANX", getFloat(PARAM_VOLUME_VAS_PHALANX));
    env.newProperty<float>("PARAM_VOLUME_VAS_TIP", getFloat(PARAM_VOLUME_VAS_TIP));
    env.newProperty<float>("PARAM_ECM_DEPOSITION_RATE", getFloat(PARAM_ECM_DEPOSITION_RATE));
    env.newProperty<float>("PARAM_ECM_DENSITY_CAP", getFloat(PARAM_ECM_DENSITY_CAP));
    env.newProperty<float>("PARAM_ECM_MMP_DEGRADE_RATE", getFloat(PARAM_ECM_MMP_DEGRADE_RATE));
    env.newProperty<float>("PARAM_ECM_CROSSLINK_RATE", getFloat(PARAM_ECM_CROSSLINK_RATE));
    env.newProperty<float>("PARAM_ECM_CROSSLINK_RESISTANCE", getFloat(PARAM_ECM_CROSSLINK_RESISTANCE));
    env.newProperty<float>("PARAM_ECM_DECAY_RATE", getFloat(PARAM_ECM_DECAY_RATE));
    env.newProperty<float>("PARAM_ECM_BASELINE", getFloat(PARAM_ECM_BASELINE));
    env.newProperty<float>("PARAM_ECM_TGFB_EC50", getFloat(PARAM_ECM_TGFB_EC50));
    env.newProperty<float>("PARAM_ECM_POROSITY_CANCER", getFloat(PARAM_ECM_POROSITY_CANCER));
    env.newProperty<float>("PARAM_ECM_POROSITY_TCELL", getFloat(PARAM_ECM_POROSITY_TCELL));
    env.newProperty<float>("PARAM_ECM_POROSITY_TREG", getFloat(PARAM_ECM_POROSITY_TREG));
    env.newProperty<float>("PARAM_ECM_POROSITY_MDSC", getFloat(PARAM_ECM_POROSITY_MDSC));
    env.newProperty<float>("PARAM_ECM_POROSITY_MAC", getFloat(PARAM_ECM_POROSITY_MAC));
    env.newProperty<float>("PARAM_ECM_POROSITY_FIB", getFloat(PARAM_ECM_POROSITY_FIB));
    env.newProperty<float>("PARAM_ECM_POROSITY_VAS_TIP", getFloat(PARAM_ECM_POROSITY_VAS_TIP));
    env.newProperty<float>("PARAM_VAS_ECM_COMPRESS_K", getFloat(PARAM_VAS_ECM_COMPRESS_K));
    env.newProperty<float>("PARAM_ECM_YAP_EC50", getFloat(PARAM_ECM_YAP_EC50));
    env.newProperty<float>("PARAM_DOMAIN_LOBULE_SPACING", getFloat(PARAM_DOMAIN_LOBULE_SPACING));
    env.newProperty<float>("PARAM_DOMAIN_SEPTUM_THICKNESS", getFloat(PARAM_DOMAIN_SEPTUM_THICKNESS));
    env.newProperty<float>("PARAM_DOMAIN_TUMOR_RADIUS_FRAC", getFloat(PARAM_DOMAIN_TUMOR_RADIUS_FRAC));
    env.newProperty<float>("PARAM_DOMAIN_MARGIN_THICKNESS", getFloat(PARAM_DOMAIN_MARGIN_THICKNESS));
    env.newProperty<float>("PARAM_DOMAIN_ECM_SEPTUM_DENSITY", getFloat(PARAM_DOMAIN_ECM_SEPTUM_DENSITY));
    env.newProperty<float>("PARAM_DOMAIN_ECM_SEPTUM_CROSSLINK", getFloat(PARAM_DOMAIN_ECM_SEPTUM_CROSSLINK));
    env.newProperty<float>("PARAM_DOMAIN_ECM_STROMA_DENSITY", getFloat(PARAM_DOMAIN_ECM_STROMA_DENSITY));
    env.newProperty<float>("PARAM_DOMAIN_ECM_LOBULE_DENSITY", getFloat(PARAM_DOMAIN_ECM_LOBULE_DENSITY));
    env.newProperty<float>("PARAM_DOMAIN_ECM_MARGIN_DENSITY", getFloat(PARAM_DOMAIN_ECM_MARGIN_DENSITY));
    env.newProperty<float>("PARAM_DOMAIN_ECM_MARGIN_CROSSLINK", getFloat(PARAM_DOMAIN_ECM_MARGIN_CROSSLINK));
    env.newProperty<float>("PARAM_DOMAIN_ECM_TUMOR_DENSITY", getFloat(PARAM_DOMAIN_ECM_TUMOR_DENSITY));
    env.newProperty<float>("PARAM_DOMAIN_FIB_P_SEPTUM", getFloat(PARAM_DOMAIN_FIB_P_SEPTUM));
    env.newProperty<float>("PARAM_DOMAIN_FIB_P_STROMA", getFloat(PARAM_DOMAIN_FIB_P_STROMA));
    env.newProperty<float>("PARAM_DOMAIN_FIB_P_LOBULE", getFloat(PARAM_DOMAIN_FIB_P_LOBULE));
    env.newProperty<float>("PARAM_DOMAIN_FIB_P_MARGIN", getFloat(PARAM_DOMAIN_FIB_P_MARGIN));
    env.newProperty<float>("PARAM_DOMAIN_FIB_P_TUMOR", getFloat(PARAM_DOMAIN_FIB_P_TUMOR));
    env.newProperty<float>("PARAM_DOMAIN_FIB_MARGIN_MYCAF_FRAC", getFloat(PARAM_DOMAIN_FIB_MARGIN_MYCAF_FRAC));
    env.newProperty<float>("PARAM_DOMAIN_VAS_P_SEPTUM", getFloat(PARAM_DOMAIN_VAS_P_SEPTUM));
    env.newProperty<float>("PARAM_DOMAIN_VAS_P_STROMA", getFloat(PARAM_DOMAIN_VAS_P_STROMA));
    env.newProperty<float>("PARAM_DOMAIN_VAS_P_LOBULE", getFloat(PARAM_DOMAIN_VAS_P_LOBULE));
    env.newProperty<float>("PARAM_DOMAIN_VAS_P_MARGIN", getFloat(PARAM_DOMAIN_VAS_P_MARGIN));
    env.newProperty<float>("PARAM_DOMAIN_VAS_P_TUMOR", getFloat(PARAM_DOMAIN_VAS_P_TUMOR));
    env.newProperty<float>("PARAM_DOMAIN_VAS_MARGIN_TIP_FRAC", getFloat(PARAM_DOMAIN_VAS_MARGIN_TIP_FRAC));
    env.newProperty<float>("PARAM_DOMAIN_MAC_P_STROMA", getFloat(PARAM_DOMAIN_MAC_P_STROMA));
    env.newProperty<float>("PARAM_DOMAIN_MAC_P_MARGIN", getFloat(PARAM_DOMAIN_MAC_P_MARGIN));
    env.newProperty<float>("PARAM_DOMAIN_MAC_P_TUMOR", getFloat(PARAM_DOMAIN_MAC_P_TUMOR));
    env.newProperty<float>("PARAM_DOMAIN_MAC_MARGIN_M1_FRAC", getFloat(PARAM_DOMAIN_MAC_MARGIN_M1_FRAC));
    env.newProperty<float>("PARAM_DOMAIN_TH_P_STROMA", getFloat(PARAM_DOMAIN_TH_P_STROMA));
    env.newProperty<float>("PARAM_PERSIST_TCELL_EFF", getFloat(PARAM_PERSIST_TCELL_EFF));
    env.newProperty<float>("PARAM_PERSIST_TCELL_CYT", getFloat(PARAM_PERSIST_TCELL_CYT));
    env.newProperty<float>("PARAM_PERSIST_TCELL_SUP", getFloat(PARAM_PERSIST_TCELL_SUP));
    env.newProperty<float>("PARAM_PERSIST_MAC_M1", getFloat(PARAM_PERSIST_MAC_M1));
    env.newProperty<float>("PARAM_PERSIST_MAC_M2", getFloat(PARAM_PERSIST_MAC_M2));
    env.newProperty<float>("PARAM_PERSIST_FIB_MYCAF", getFloat(PARAM_PERSIST_FIB_MYCAF));
    env.newProperty<float>("PARAM_PERSIST_FIB_ICAF", getFloat(PARAM_PERSIST_FIB_ICAF));
    env.newProperty<float>("PARAM_PERSIST_VAS_TIP", getFloat(PARAM_PERSIST_VAS_TIP));
    env.newProperty<float>("PARAM_PERSIST_TREG_REG", getFloat(PARAM_PERSIST_TREG_REG));
    env.newProperty<float>("PARAM_PERSIST_TREG_TH", getFloat(PARAM_PERSIST_TREG_TH));
    env.newProperty<float>("PARAM_PERSIST_MDSC", getFloat(PARAM_PERSIST_MDSC));
    env.newProperty<float>("PARAM_CHEMO_BIAS_CANCER_STEM", getFloat(PARAM_CHEMO_BIAS_CANCER_STEM));
    env.newProperty<float>("PARAM_CHEMO_BIAS_MAC_M1", getFloat(PARAM_CHEMO_BIAS_MAC_M1));
    env.newProperty<float>("PARAM_CHEMO_BIAS_MAC_M2", getFloat(PARAM_CHEMO_BIAS_MAC_M2));
    env.newProperty<float>("PARAM_CHEMO_BIAS_FIB_MYCAF", getFloat(PARAM_CHEMO_BIAS_FIB_MYCAF));
    env.newProperty<float>("PARAM_CHEMO_BIAS_VAS_TIP", getFloat(PARAM_CHEMO_BIAS_VAS_TIP));
    env.newProperty<float>("PARAM_CHEMO_BIAS_TREG_REG", getFloat(PARAM_CHEMO_BIAS_TREG_REG));
    env.newProperty<float>("PARAM_CHEMO_BIAS_MDSC", getFloat(PARAM_CHEMO_BIAS_MDSC));
    env.newProperty<float>("PARAM_ADH_ECM_DENSITY_TH", getFloat(PARAM_ADH_ECM_DENSITY_TH));
    env.newProperty<float>("PARAM_ADH_CANCER_STEM_CANCER", getFloat(PARAM_ADH_CANCER_STEM_CANCER));
    env.newProperty<float>("PARAM_ADH_CANCER_STEM_FIB", getFloat(PARAM_ADH_CANCER_STEM_FIB));
    env.newProperty<float>("PARAM_ADH_CANCER_STEM_ECM", getFloat(PARAM_ADH_CANCER_STEM_ECM));
    env.newProperty<float>("PARAM_ADH_CANCER_PROG_CANCER", getFloat(PARAM_ADH_CANCER_PROG_CANCER));
    env.newProperty<float>("PARAM_ADH_CANCER_PROG_FIB", getFloat(PARAM_ADH_CANCER_PROG_FIB));
    env.newProperty<float>("PARAM_ADH_CANCER_PROG_ECM", getFloat(PARAM_ADH_CANCER_PROG_ECM));
    env.newProperty<float>("PARAM_ADH_TCELL_CYT_CANCER", getFloat(PARAM_ADH_TCELL_CYT_CANCER));
    env.newProperty<float>("PARAM_ADH_MAC_M2_CANCER", getFloat(PARAM_ADH_MAC_M2_CANCER));
    env.newProperty<float>("PARAM_ADH_MAC_M2_FIB", getFloat(PARAM_ADH_MAC_M2_FIB));
    env.newProperty<float>("PARAM_ADH_MAC_M2_ECM", getFloat(PARAM_ADH_MAC_M2_ECM));
    env.newProperty<float>("PARAM_ADH_FIB_MYCAF_CANCER", getFloat(PARAM_ADH_FIB_MYCAF_CANCER));
    env.newProperty<float>("PARAM_ADH_FIB_MYCAF_FIB", getFloat(PARAM_ADH_FIB_MYCAF_FIB));
    env.newProperty<float>("PARAM_ADH_FIB_MYCAF_ECM", getFloat(PARAM_ADH_FIB_MYCAF_ECM));
    env.newProperty<float>("PARAM_ADH_FIB_ICAF_CANCER", getFloat(PARAM_ADH_FIB_ICAF_CANCER));
    env.newProperty<float>("PARAM_ADH_FIB_ICAF_FIB", getFloat(PARAM_ADH_FIB_ICAF_FIB));
    env.newProperty<float>("PARAM_ADH_FIB_ICAF_ECM", getFloat(PARAM_ADH_FIB_ICAF_ECM));
    env.newProperty<float>("PARAM_IFNG_DIFFUSIVITY", getFloat(PARAM_IFNG_DIFFUSIVITY));
    env.newProperty<float>("PARAM_IFNG_RELEASE", getFloat(PARAM_IFNG_RELEASE));
    env.newProperty<float>("PARAM_IFNG_DECAY_RATE", getFloat(PARAM_IFNG_DECAY_RATE));
    env.newProperty<float>("PARAM_IFNG_MOLECULAR_WEIGHT", getFloat(PARAM_IFNG_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_IL2_DIFFUSIVITY", getFloat(PARAM_IL2_DIFFUSIVITY));
    env.newProperty<float>("PARAM_IL2_RELEASE", getFloat(PARAM_IL2_RELEASE));
    env.newProperty<float>("PARAM_IL2_UPTAKE", getFloat(PARAM_IL2_UPTAKE));
    env.newProperty<float>("PARAM_IL2_DECAY_RATE", getFloat(PARAM_IL2_DECAY_RATE));
    env.newProperty<float>("PARAM_IL2_MOLECULAR_WEIGHT", getFloat(PARAM_IL2_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_CCL2_DIFFUSIVITY", getFloat(PARAM_CCL2_DIFFUSIVITY));
    env.newProperty<float>("PARAM_CCL2_RELEASE", getFloat(PARAM_CCL2_RELEASE));
    env.newProperty<float>("PARAM_CCL2_UPTAKE", getFloat(PARAM_CCL2_UPTAKE));
    env.newProperty<float>("PARAM_CCL2_DECAY_RATE", getFloat(PARAM_CCL2_DECAY_RATE));
    env.newProperty<float>("PARAM_CCL2_MOLECULAR_WEIGHT", getFloat(PARAM_CCL2_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_ARGI_DIFFUSIVITY", getFloat(PARAM_ARGI_DIFFUSIVITY));
    env.newProperty<float>("PARAM_ARGI_RELEASE", getFloat(PARAM_ARGI_RELEASE));
    env.newProperty<float>("PARAM_ARGI_DECAY_RATE", getFloat(PARAM_ARGI_DECAY_RATE));
    env.newProperty<float>("PARAM_ARGI_MOLECULAR_WEIGHT", getFloat(PARAM_ARGI_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_NO_DIFFUSIVITY", getFloat(PARAM_NO_DIFFUSIVITY));
    env.newProperty<float>("PARAM_NO_RELEASE", getFloat(PARAM_NO_RELEASE));
    env.newProperty<float>("PARAM_NO_DECAY_RATE", getFloat(PARAM_NO_DECAY_RATE));
    env.newProperty<float>("PARAM_NO_MOLECULAR_WEIGHT", getFloat(PARAM_NO_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_TGFB_DIFFUSIVITY", getFloat(PARAM_TGFB_DIFFUSIVITY));
    env.newProperty<float>("PARAM_TREG_TGFB_RELEASE", getFloat(PARAM_TREG_TGFB_RELEASE));
    env.newProperty<float>("PARAM_MAC_TGFB_RELEASE", getFloat(PARAM_MAC_TGFB_RELEASE));
    env.newProperty<float>("PARAM_STEM_TGFB_RELEASE", getFloat(PARAM_STEM_TGFB_RELEASE));
    env.newProperty<float>("PARAM_PROG_TGFB_RELEASE", getFloat(PARAM_PROG_TGFB_RELEASE));
    env.newProperty<float>("PARAM_TGFB_DECAY_RATE", getFloat(PARAM_TGFB_DECAY_RATE));
    env.newProperty<float>("PARAM_TGFB_MOLECULAR_WEIGHT", getFloat(PARAM_TGFB_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_IL10_DIFFUSIVITY", getFloat(PARAM_IL10_DIFFUSIVITY));
    env.newProperty<float>("PARAM_TREG_IL10_RELEASE", getFloat(PARAM_TREG_IL10_RELEASE));
    env.newProperty<float>("PARAM_MAC_IL10_RELEASE", getFloat(PARAM_MAC_IL10_RELEASE));
    env.newProperty<float>("PARAM_IL10_DECAY_RATE", getFloat(PARAM_IL10_DECAY_RATE));
    env.newProperty<float>("PARAM_IL10_MOLECULAR_WEIGHT", getFloat(PARAM_IL10_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_IL12_DIFFUSIVITY", getFloat(PARAM_IL12_DIFFUSIVITY));
    env.newProperty<float>("PARAM_IL12_RELEASE", getFloat(PARAM_IL12_RELEASE));
    env.newProperty<float>("PARAM_IL12_DECAY_RATE", getFloat(PARAM_IL12_DECAY_RATE));
    env.newProperty<float>("PARAM_IL12_MOLECULAR_WEIGHT", getFloat(PARAM_IL12_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_VEGFA_DIFFUSIVITY", getFloat(PARAM_VEGFA_DIFFUSIVITY));
    env.newProperty<float>("PARAM_MAC_VEGFA_RELEASE", getFloat(PARAM_MAC_VEGFA_RELEASE));
    env.newProperty<float>("PARAM_STEM_VEGFA_RELEASE", getFloat(PARAM_STEM_VEGFA_RELEASE));
    env.newProperty<float>("PARAM_PROG_VEGFA_RELEASE", getFloat(PARAM_PROG_VEGFA_RELEASE));
    env.newProperty<float>("PARAM_VEGFA_UPTAKE", getFloat(PARAM_VEGFA_UPTAKE));
    env.newProperty<float>("PARAM_VEGFA_DECAY_RATE", getFloat(PARAM_VEGFA_DECAY_RATE));
    env.newProperty<float>("PARAM_VEGFA_MOLECULAR_WEIGHT", getFloat(PARAM_VEGFA_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_O2_DIFFUSIVITY", getFloat(PARAM_O2_DIFFUSIVITY));
    env.newProperty<float>("PARAM_O2_UPTAKE", getFloat(PARAM_O2_UPTAKE));
    env.newProperty<float>("PARAM_O2_DECAY_RATE", getFloat(PARAM_O2_DECAY_RATE));
    env.newProperty<float>("PARAM_O2_MOLECULAR_WEIGHT", getFloat(PARAM_O2_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_IL1_DIFFUSIVITY", getFloat(PARAM_IL1_DIFFUSIVITY));
    env.newProperty<float>("PARAM_CANCER_IL1_RELEASE_STEM", getFloat(PARAM_CANCER_IL1_RELEASE_STEM));
    env.newProperty<float>("PARAM_CANCER_IL1_RELEASE_PROG", getFloat(PARAM_CANCER_IL1_RELEASE_PROG));
    env.newProperty<float>("PARAM_CANCER_IL1_RELEASE_SEN", getFloat(PARAM_CANCER_IL1_RELEASE_SEN));
    env.newProperty<float>("PARAM_MAC_M1_IL1_RELEASE", getFloat(PARAM_MAC_M1_IL1_RELEASE));
    env.newProperty<float>("PARAM_IL1_DECAY_RATE", getFloat(PARAM_IL1_DECAY_RATE));
    env.newProperty<float>("PARAM_IL1_MOLECULAR_WEIGHT", getFloat(PARAM_IL1_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_IL6_DIFFUSIVITY", getFloat(PARAM_IL6_DIFFUSIVITY));
    env.newProperty<float>("PARAM_IL6_DECAY_RATE", getFloat(PARAM_IL6_DECAY_RATE));
    env.newProperty<float>("PARAM_IL6_MOLECULAR_WEIGHT", getFloat(PARAM_IL6_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_CXCL13_DIFFUSIVITY", getFloat(PARAM_CXCL13_DIFFUSIVITY));
    env.newProperty<float>("PARAM_CXCL13_DECAY_RATE", getFloat(PARAM_CXCL13_DECAY_RATE));
    env.newProperty<float>("PARAM_CXCL13_MOLECULAR_WEIGHT", getFloat(PARAM_CXCL13_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_MMP_DIFFUSIVITY", getFloat(PARAM_MMP_DIFFUSIVITY));
    env.newProperty<float>("PARAM_MMP_DECAY_RATE", getFloat(PARAM_MMP_DECAY_RATE));
    env.newProperty<float>("PARAM_MMP_MOLECULAR_WEIGHT", getFloat(PARAM_MMP_MOLECULAR_WEIGHT));
    env.newProperty<float>("PARAM_CANCER_MMP_RELEASE", getFloat(PARAM_CANCER_MMP_RELEASE));
    env.newProperty<float>("PARAM_MAC_M1_MMP_RELEASE", getFloat(PARAM_MAC_M1_MMP_RELEASE));
    env.newProperty<float>("PARAM_WEIGHT_QSP", getFloat(PARAM_WEIGHT_QSP));

    env.newProperty<int>("PARAM_SHUFFLE_INTERVAL", getInt(PARAM_SHUFFLE_INTERVAL));
    env.newProperty<int>("PARAM_GRID_SHIFT_INTERVAL", getInt(PARAM_GRID_SHIFT_INTERVAL));
    env.newProperty<int>("PARAM_X_SIZE", getInt(PARAM_X_SIZE));
    env.newProperty<int>("PARAM_Y_SIZE", getInt(PARAM_Y_SIZE));
    env.newProperty<int>("PARAM_Z_SIZE", getInt(PARAM_Z_SIZE));
    env.newProperty<int>("PARAM_VOXEL_SIZE", getInt(PARAM_VOXEL_SIZE));
    env.newProperty<int>("PARAM_NR_T_VOXELS", getInt(PARAM_NR_T_VOXELS));
    env.newProperty<int>("PARAM_NR_T_VOXELS_C", getInt(PARAM_NR_T_VOXELS_C));
    env.newProperty<int>("PARAM_STEM_MODE", getInt(PARAM_STEM_MODE));
    env.newProperty<int>("PARAM_TCELL_DIV_INTERNAL", getInt(PARAM_TCELL_DIV_INTERNAL));
    env.newProperty<int>("PARAM_TCELL_DIV_LIMIT", getInt(PARAM_TCELL_DIV_LIMIT));
    env.newProperty<int>("PARAM_TCELL_MOVE_STEPS", getInt(PARAM_TCELL_MOVE_STEPS));
    env.newProperty<int>("PARAM_TCD4_DIV_INTERNAL", getInt(PARAM_TCD4_DIV_INTERNAL));
    env.newProperty<int>("PARAM_TCD4_DIV_LIMIT", getInt(PARAM_TCD4_DIV_LIMIT));
    env.newProperty<int>("PARAM_MDSC_MOVE_STEPS", getInt(PARAM_MDSC_MOVE_STEPS));
    env.newProperty<int>("PARAM_MAC_MOVE_STEPS", getInt(PARAM_MAC_MOVE_STEPS));
    env.newProperty<int>("PARAM_PROG_DIV_MAX", getInt(PARAM_PROG_DIV_MAX));
    env.newProperty<int>("PARAM_CANCER_MOVE_STEPS", getInt(PARAM_CANCER_MOVE_STEPS));
    env.newProperty<int>("PARAM_CANCER_MOVE_STEPS_STEM", getInt(PARAM_CANCER_MOVE_STEPS_STEM));
    env.newProperty<int>("PARAM_FIB_MOVE_STEPS", getInt(PARAM_FIB_MOVE_STEPS));
    env.newProperty<int>("PARAM_DOMAIN_PDE_WARMUP_SUBSTEPS", getInt(PARAM_DOMAIN_PDE_WARMUP_SUBSTEPS));
    env.newProperty<int>("PARAM_MOLECULAR_STEPS", getInt(PARAM_MOLECULAR_STEPS));

    env.newProperty<bool>("PARAM_NIVO_ON", getBool(PARAM_NIVO_ON));
    env.newProperty<bool>("PARAM_IPI_ON", getBool(PARAM_IPI_ON));
    env.newProperty<bool>("PARAM_CABO_ON", getBool(PARAM_CABO_ON));
    env.newProperty<bool>("PARAM_ENT_ON", getBool(PARAM_ENT_ON));

    // Computed properties
    // total voxel count
    env.newProperty<float>("PARAM_GRID_SIZE", static_cast<float>(getInt(PARAM_X_SIZE) * getInt(PARAM_Y_SIZE) * getInt(PARAM_Z_SIZE)));

}

} // namespace PDAC
