#include "flamegpu/flamegpu.h"
#include "../core/common.cuh"
#include "../qsp/LymphCentral_wrapper.h"
#include "../qsp/ode/QSP_enum.h"
#include "../pde/pde_integration.cuh"
#include <nvtx3/nvToolsExt.h>
#define QP(x) CancerVCT::ODE_system::get_class_param(x)

#define AVOGADROS 6.022140857E23
#define PI 3.1415926525897932384626
static int SEC_PER_DAY = 86400;
static int HOUR_PER_DAY = 24;

namespace PDAC {

void set_internal_params(flamegpu::ModelDescription& model, const PDAC::LymphCentralWrapper& lymph){
    flamegpu::EnvironmentDescription env = model.Environment();

    // Auto-generated derived parameters from DerivedParams section of param_all_test.xml
    // Generated by abm_param_codegen.py — see PDAC/codegen/abm_param_codegen.py
#include "../abm/derived_params.inc"

}

FLAMEGPU_HOST_FUNCTION(update_agent_counts) {
    nvtxRangePush("Update Agent Counts");
    // Get counts for each agent type
    int cancer_count = FLAMEGPU->agent(AGENT_CANCER_CELL).count();
    int tcell_count = FLAMEGPU->agent(AGENT_TCELL).count();
    int treg_count = FLAMEGPU->agent(AGENT_TREG).count();
    int mdsc_count = FLAMEGPU->agent(AGENT_MDSC).count();

    // Update environment properties
    FLAMEGPU->environment.setProperty<unsigned int>("total_cancer_cells", cancer_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_tcells", tcell_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_tregs", treg_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_mdscs", mdsc_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_agents",
    cancer_count + tcell_count + treg_count + mdsc_count);
    nvtxRangePop();
}


}

