#include "flamegpu/flamegpu.h"
#include "../core/common.cuh"
#include "../qsp/LymphCentral_wrapper.h"
#include "../qsp/ode/QSP_enum.h"
#include "../pde/pde_integration.cuh"
#include <nvtx3/nvToolsExt.h>
#define QP(x) CancerVCT::ODE_system::get_class_param(x)

#define AVOGADROS 6.022140857E23
#define PI 3.1415926525897932384626
static int SEC_PER_DAY = 86400;
static int HOUR_PER_DAY = 24;

namespace PDAC {

void set_internal_params(flamegpu::ModelDescription& model, const PDAC::LymphCentralWrapper& lymph){
    flamegpu::EnvironmentDescription env = model.Environment();

    // Auto-generated derived parameters from DerivedParams section of param_all_test.xml
    // Generated by abm_param_codegen.py — see PDAC/codegen/abm_param_codegen.py
#include "../abm/derived_params.inc"

}

FLAMEGPU_HOST_FUNCTION(update_agent_counts) {
    nvtxRangePush("Update Agent Counts");
    // Get counts for each agent type
    int cancer_count = FLAMEGPU->agent(AGENT_CANCER_CELL).count();
    int tcell_count = FLAMEGPU->agent(AGENT_TCELL).count();
    int treg_count = FLAMEGPU->agent(AGENT_TREG).count();
    int mdsc_count = FLAMEGPU->agent(AGENT_MDSC).count();

    // Update environment properties
    FLAMEGPU->environment.setProperty<unsigned int>("total_cancer_cells", cancer_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_tcells", tcell_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_tregs", treg_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_mdscs", mdsc_count);
    FLAMEGPU->environment.setProperty<unsigned int>("total_agents",
    cancer_count + tcell_count + treg_count + mdsc_count);
    nvtxRangePop();
}

FLAMEGPU_HOST_FUNCTION(check_cancer_count_before_movement) {
    unsigned int step = FLAMEGPU->environment.getProperty<unsigned int>("current_step");
    int cancer_count = FLAMEGPU->agent(AGENT_CANCER_CELL).count();

    std::cout << "Step " << step << " - Cancer cells before movement: " << cancer_count << std::endl;

}

FLAMEGPU_HOST_FUNCTION(reset_division_counters) {
    FLAMEGPU->environment.setProperty<unsigned int>("cancer_divide_attempts", 0u);
    FLAMEGPU->environment.setProperty<unsigned int>("cancer_divide_successes", 0u);
    FLAMEGPU->environment.setProperty<unsigned int>("tcell_divide_attempts", 0u);
    FLAMEGPU->environment.setProperty<unsigned int>("tcell_divide_successes", 0u);
    FLAMEGPU->environment.setProperty<unsigned int>("treg_divide_attempts", 0u);
    FLAMEGPU->environment.setProperty<unsigned int>("treg_divide_successes", 0u);
}

FLAMEGPU_HOST_FUNCTION(report_division_statistics) {
    unsigned int step = FLAMEGPU->environment.getProperty<unsigned int>("current_step");
    unsigned int cancer_attempts = FLAMEGPU->environment.getProperty<unsigned int>("cancer_divide_attempts");
    unsigned int cancer_successes = FLAMEGPU->environment.getProperty<unsigned int>("cancer_divide_successes");
    unsigned int tcell_attempts = FLAMEGPU->environment.getProperty<unsigned int>("tcell_divide_attempts");
    unsigned int tcell_successes = FLAMEGPU->environment.getProperty<unsigned int>("tcell_divide_successes");
    unsigned int treg_attempts = FLAMEGPU->environment.getProperty<unsigned int>("treg_divide_attempts");
    unsigned int treg_successes = FLAMEGPU->environment.getProperty<unsigned int>("treg_divide_successes");

    std::cout << "Step " << step << " - Division Stats:"
              << " Cancer(A:" << cancer_attempts << " S:" << cancer_successes << ")"
              << " TCell(A:" << tcell_attempts << " S:" << tcell_successes << ")"
              << " TReg(A:" << treg_attempts << " S:" << treg_successes << ")"
              << std::endl;
}

FLAMEGPU_HOST_FUNCTION(check_cancer_count_after_movement) {
    unsigned int step = FLAMEGPU->environment.getProperty<unsigned int>("current_step");
    int cancer_count = FLAMEGPU->agent(AGENT_CANCER_CELL).count();

    std::cout << "Step " << step << " - Cancer cells after movement: " << cancer_count << std::endl;

}

FLAMEGPU_HOST_FUNCTION(check_voxel_occupancy) {
    unsigned int step = FLAMEGPU->environment.getProperty<unsigned int>("current_step");
    int cancer_count = FLAMEGPU->agent(AGENT_CANCER_CELL).count();
    std::cout << "Step " << step << " - Cancer cell count (before division): " << cancer_count << std::endl;
}

FLAMEGPU_HOST_FUNCTION(check_voxel_packing_after_movement) {
    // Placeholder - the real issue is in execute_move and execute_divide
    // Both need to check MSG_CELL_LOCATION to verify target voxel is physically empty
}

}

